import turtle
isaiah = turtle.Turtle()
paige = turtle.Turtle()
dyson = turtle.Turtle()
jarrett = turtle.Turtle()
isaiah.color("dark slate blue")
dyson.color("firebrick")
def square():
    for i in range (4):
        isaiah.forward(200)
        isaiah.right(90)
square()
isaiah.left(60)
isaiah.forward(100)
isaiah.right(60)
isaiah.forward(80)
isaiah.left(90)
isaiah.forward(50)
isaiah.right(90)
isaiah.forward(50)
isaiah.right(90)
isaiah.forward(70)
isaiah.left(15)
isaiah.forward(70)
paige.pu()
paige.goto(45,-45)
paige.pd()
def square2():
    for i in range (4):
        paige.forward(50)
        paige.right(90)
square2()
paige.forward(25)
paige.right(90)
paige.forward(50)
paige.backward(25)
paige.left(90)
paige.forward(25)
paige.backward(50)
paige.pu()
paige.forward(75)
paige.pd()
square2()
paige.forward(25)
paige.right(90)
paige.forward(50)
paige.backward(25)
paige.left(90)
paige.forward(25)
paige.backward(50)

dyson.pu()
dyson.goto(90,-200)
dyson.begin_fill()
dyson.fillcolor("firebrick")
dyson.left(90)
dyson.pd()
dyson.forward(65)
dyson.right(90)
dyson.forward(40)
dyson.right(90)
dyson.forward(65)
dyson.end_fill()


turtle.exitonclick()