import turtle
isaiah = turtle.Turtle()
paige = turtle.Turtle()
dyson = turtle.Turtle()
jarrett = turtle.Turtle()
isaiah.color("dark slate blue")
dyson.color("firebrick")
paige.color("dark olive green")
jarrett.speed(5)

jarrett.right(90)
jarrett.pu()
jarrett.forward(200)
jarrett.left(90)
jarrett.pd()
def square3():
    for i in range (1):
        jarrett.forward(355)
        jarrett.right(90)
        jarrett.forward(130)
        jarrett.right(90)
        jarrett.forward(715)
        jarrett.right(90)
        jarrett.forward(130)
        jarrett.right(90)
        jarrett.forward(360)
jarrett.begin_fill()
jarrett.fillcolor("forest green")
square3()
jarrett.end_fill()
jarrett.begin_fill()
jarrett.fillcolor("deep sky blue")
jarrett.backward(360)
jarrett.left(90)
jarrett.forward(570)
jarrett.right(90)
jarrett.forward(715)
jarrett.right(90)
jarrett.forward(570)
jarrett.right(90)
jarrett.forward(355)
jarrett.end_fill()

def square():
    for i in range (4):
        isaiah.forward(200)
        isaiah.right(90)
isaiah.begin_fill()
isaiah.fillcolor("burlywood")
square()
isaiah.end_fill()
isaiah.begin_fill()
isaiah.fillcolor("firebrick")
isaiah.left(60)
isaiah.forward(100)
isaiah.right(60)
isaiah.forward(80)
isaiah.left(90)
isaiah.forward(50)
isaiah.right(90)
isaiah.forward(50)
isaiah.right(90)
isaiah.forward(70)
isaiah.left(15)
isaiah.forward(70)
isaiah.end_fill()

paige.pu()
paige.goto(45,-45)
paige.pd()
def square2():
    for i in range (4):
        paige.forward(50)
        paige.right(90)
paige.begin_fill()
paige.fillcolor("light gray")
square2()
paige.forward(25)
paige.right(90)
paige.forward(50)
paige.backward(25)
paige.left(90)
paige.forward(25)
paige.backward(50)
paige.end_fill()
paige.pu()
paige.forward(75)
paige.pd()
paige.begin_fill()
paige.fillcolor("light gray")
square2()
paige.forward(25)
paige.right(90)
paige.forward(50)
paige.backward(25)
paige.left(90)
paige.forward(25)
paige.backward(50)
paige.end_fill()

dyson.pu()
dyson.goto(90,-200)
dyson.begin_fill()
dyson.fillcolor("firebrick")
dyson.left(90)
dyson.pd()
dyson.forward(65)
dyson.right(90)
dyson.forward(40)
dyson.right(90)
dyson.forward(65)
dyson.end_fill()
dyson.backward(35)
dyson.right(90)
dyson.forward(10)
dyson.begin_fill()
dyson.fillcolor("goldenrod")
dyson.circle(3)
dyson.end_fill()

isaiah.pu()
isaiah.goto(-90,-200)
isaiah.left(75)
isaiah.forward(180)
isaiah.right(90)
isaiah.pd()
isaiah.forward(20)

def curve():
    for i in range (3):
        isaiah.forward(10)
        isaiah.left(20)
        isaiah.forward(10)
        isaiah.left(10)

curve()

isaiah.forward(90)
isaiah.right(90)
isaiah.forward(70)
isaiah.left(90)
isaiah.forward(140)
isaiah.left(90)
isaiah.forward(130)
isaiah.left(90)
isaiah.forward(160)






turtle.exitonclick()